name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: sbt test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for scalafmt conformance
      uses: openlawteam/scalafmt-ci@v2
      with:
        args: "--exclude=third_party --list"
