name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run test
      env:
        ESMETA_HOME: ${{ github.workspace }}
        JVM_OPTS: -Xms16g -Xmx32g -Xss1g -Xmn512m -Dfile.encoding=utf8
      run: sbt test
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check code format
      run: sbt scalafmtSbtCheck scalafmtCheck "Test / scalafmtCheck"
